export {default as Home} from "../components/home/Home"
export {default as Sidebar} from "../components/sidebar/Sidebar"
export {default as Profile} from "../components/profile/Profile"
export {default as AllMeme} from "../components/all-meme/AllMeme"
export {default as MemeGallery} from "../components/gallery/MemeGallery"
// export {default as Profile} from "../components/profile/Profile"
export {default as MemeStream} from "../components/meme-stream/MemeStream"
export {default as Editor} from "../components/editor/Editor"